!pip install ydata-profiling
from ydata_profiling import ProfileReport

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab Notebooks/Dirty Cafe Data Cleaning/dirty_cafe_sales.csv'
df = pd.read_csv(file_path)

profile = ProfileReport(df, title="Dirty Cafe Sales Report", explorative=True)

display(profile.to_notebook_iframe())

from google.colab import data_table
data_table.enable_dataframe_formatter()

cleaning = ["ERROR", "UNKNOWN", "Missing value", "nan", "missing value", "", " "]
df = df.replace(cleaning, np.nan)

df = df.astype({'Payment Method': str, 'Location': str})


df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors='coerce')
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors='coerce')
df["Transaction Date"] = pd.to_datetime(df['Transaction Date'], errors='coerce')

mean_prices = df.dropna(subset=["Price Per Unit"]).groupby("Item")["Price Per Unit"].mean()
print(mean_prices)

def missing(df):
  price_change = {'Cake': 3.00, 'Coffee': 2.00, 'Cookie': 1.00, 'Juice': 3.00, 'Pastry': 2.50, 'Salad': 5.00, 'Sandwich': 4.00, 'Smoothie': 4.00, 'Tea': 1.50}
  def fill(row):
    item = row['Item']
    price = row['Price Per Unit']

    if item in price_change:
      if pd.isna(price):
        return price_change[item]
      else:
        return price
    return price

  df['Price Per Unit'] = df.apply(fill, axis=1)
  return df

missing(df)

df["Total Spent"] = df["Quantity"] * df["Price Per Unit"]

df = df.dropna(subset=['Quantity', 'Price Per Unit']).copy()

profile = ProfileReport(df, title="Dirty Cafe Sales Report", explorative=True)

display(profile.to_notebook_iframe())

plt.style.use('bmh')

print("\nWhat is the total revenue generated by each item?")
revenue_by_item = df.groupby('Item')['Total Spent'].sum().sort_values(ascending=False)
print(revenue_by_item)

plt.figure(figsize=(10, 6))
revenue_by_item.plot(kind='bar', color='black', alpha=0.8)
plt.title('Total Revenue Generated by Each Item')
plt.ylabel('Revenue ($)')
plt.xlabel('Item')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


print("\nWhat is the most ordered item?")
quantity_by_item = df.groupby('Item')['Quantity'].sum().sort_values(ascending=False)
top_item_name = quantity_by_item.index[0]
top_item_qty = quantity_by_item.iloc[0]
print(f"Most Ordered: {top_item_name} with {top_item_qty} units")
print(quantity_by_item)

plt.figure(figsize=(10, 6))
quantity_by_item.plot(kind='bar', color='black', alpha=0.8)
plt.title('Most Ordered Item (By Quantity)')
plt.ylabel('Quantity Sold')
plt.xlabel('Item')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()



df['Day'] = df['Transaction Date'].dt.day_name()

sales_day_descending = df.groupby("Day", observed=True)['Quantity'].sum().sort_values(ascending=False)

top_day_name = sales_day_descending.index[0]
top_day_qty = sales_day_descending.iloc[0]

print("\nOn which day of the week does the cafe see the highest sales volume?")
print(f"Busiest Day: {top_day_name} with {top_day_qty} units sold")
print("\nDay-wise Sales (Quantity Sum, Descending Order):")
print(sales_day_descending)

plt.figure(figsize=(10, 6))

sales_day_descending.plot(
    kind='bar',
    color='black',
    alpha=0.8,
)

plt.title('Sales Volume by Day of Week', fontsize=14)
plt.ylabel('Total Items Sold (Quantity)', fontsize=12)
plt.xlabel('Day of the Week', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

print("\nWhat are the revenue trends across different months?")
df['Month'] = df['Transaction Date'].dt.to_period('M')
revenue_by_month = df.groupby('Month')['Total Spent'].sum().sort_index()
print(revenue_by_month)

plt.figure(figsize=(10, 6))
revenue_by_month.plot(kind='line', marker='o', color='black', linewidth=2)
plt.title('Revenue Trends Across Months')